# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_text', models.TextField()),
                ('save_date', models.DateTimeField(verbose_name='Date Saved')),
            ],
        ),
    ]
